/**
 * PitchHeatmap
 * ------------------------------------------------------------
 * Real positional heatmap for tactical feature vectors.
 *  - `cells`: array of { x, y, weight } where x/y ∈ [0,1] and weight ∈ [0,1].
 *             When provided, renders a heat gradient by binning into a grid.
 *  - `markers`: array of { x, y, label } for formation position markers.
 *             `x` and `y` in [0,1]. Structural — always safe to render.
 *  - `formation`: optional string like "4-3-3" used to derive default markers.
 *
 * If `cells` is empty/missing the heatmap layer is not drawn — the pitch stays
 * clean and the caller can show a "backend dependency" caption alongside.
 * No fabricated data is generated by this component.
 */

const FORMATIONS = {
  "4-3-3": [
    { x: 0.08, y: 0.5, label: "GK" },
    { x: 0.22, y: 0.15, label: "LB" }, { x: 0.22, y: 0.38, label: "CB" },
    { x: 0.22, y: 0.62, label: "CB" }, { x: 0.22, y: 0.85, label: "RB" },
    { x: 0.42, y: 0.28, label: "CM" }, { x: 0.42, y: 0.5, label: "CM" }, { x: 0.42, y: 0.72, label: "CM" },
    { x: 0.72, y: 0.2, label: "LW" }, { x: 0.72, y: 0.5, label: "ST" }, { x: 0.72, y: 0.8, label: "RW" },
  ],
  "4-2-3-1": [
    { x: 0.08, y: 0.5, label: "GK" },
    { x: 0.22, y: 0.15, label: "LB" }, { x: 0.22, y: 0.38, label: "CB" },
    { x: 0.22, y: 0.62, label: "CB" }, { x: 0.22, y: 0.85, label: "RB" },
    { x: 0.4, y: 0.38, label: "DM" }, { x: 0.4, y: 0.62, label: "DM" },
    { x: 0.6, y: 0.2, label: "LM" }, { x: 0.6, y: 0.5, label: "AM" }, { x: 0.6, y: 0.8, label: "RM" },
    { x: 0.78, y: 0.5, label: "ST" },
  ],
  "3-5-2": [
    { x: 0.08, y: 0.5, label: "GK" },
    { x: 0.2, y: 0.28, label: "CB" }, { x: 0.2, y: 0.5, label: "CB" }, { x: 0.2, y: 0.72, label: "CB" },
    { x: 0.4, y: 0.12, label: "LWB" }, { x: 0.4, y: 0.36, label: "CM" }, { x: 0.4, y: 0.5, label: "CM" },
    { x: 0.4, y: 0.64, label: "CM" }, { x: 0.4, y: 0.88, label: "RWB" },
    { x: 0.72, y: 0.4, label: "ST" }, { x: 0.72, y: 0.6, label: "ST" },
  ],
  "4-4-2": [
    { x: 0.08, y: 0.5, label: "GK" },
    { x: 0.22, y: 0.15, label: "LB" }, { x: 0.22, y: 0.38, label: "CB" },
    { x: 0.22, y: 0.62, label: "CB" }, { x: 0.22, y: 0.85, label: "RB" },
    { x: 0.44, y: 0.15, label: "LM" }, { x: 0.44, y: 0.38, label: "CM" },
    { x: 0.44, y: 0.62, label: "CM" }, { x: 0.44, y: 0.85, label: "RM" },
    { x: 0.72, y: 0.38, label: "ST" }, { x: 0.72, y: 0.62, label: "ST" },
  ],
  "3-4-3": [
    { x: 0.08, y: 0.5, label: "GK" },
    { x: 0.2, y: 0.28, label: "CB" }, { x: 0.2, y: 0.5, label: "CB" }, { x: 0.2, y: 0.72, label: "CB" },
    { x: 0.42, y: 0.15, label: "LWB" }, { x: 0.42, y: 0.4, label: "CM" },
    { x: 0.42, y: 0.6, label: "CM" }, { x: 0.42, y: 0.85, label: "RWB" },
    { x: 0.72, y: 0.22, label: "LW" }, { x: 0.72, y: 0.5, label: "ST" }, { x: 0.72, y: 0.78, label: "RW" },
  ],
};

export function formationMarkers(formation) {
  return FORMATIONS[formation] || FORMATIONS["4-3-3"];
}

const GRID = 12; // 12 columns x 8 rows heat grid — enough resolution for positional intensity

export default function PitchHeatmap({
  cells,
  markers,
  formation,
  caption,
  testId = "pitch-heatmap",
  height = 260,
}) {
  const heatCells = Array.isArray(cells) && cells.length > 0 ? cells : null;
  const positions = markers || (formation ? formationMarkers(formation) : []);

  // Bin cells into a coarse grid so we render a real heatmap, not scattered dots
  let bins = null;
  if (heatCells) {
    bins = new Array(GRID * Math.round(GRID * 0.66)).fill(0);
    const rows = Math.round(GRID * 0.66);
    let maxWeight = 0;
    heatCells.forEach(({ x, y, weight = 1 }) => {
      if (typeof x !== "number" || typeof y !== "number") return;
      const cx = Math.max(0, Math.min(GRID - 1, Math.floor(x * GRID)));
      const cy = Math.max(0, Math.min(rows - 1, Math.floor(y * rows)));
      const i = cy * GRID + cx;
      bins[i] = (bins[i] || 0) + Math.max(0, weight);
      if (bins[i] > maxWeight) maxWeight = bins[i];
    });
    if (maxWeight > 0) bins = bins.map((w) => w / maxWeight);
  }

  return (
    <div
      className="pitch-visual heatmap"
      data-testid={testId}
      style={{ minHeight: height }}
      role="img"
      aria-label={caption || "Football pitch visualization"}
    >
      <div className="pitch-lines" aria-hidden="true">
        <span className="pitch-box left" />
        <span className="pitch-box right" />
        <span className="pitch-center" />
        <span className="pitch-midline" />
      </div>

      {bins && (
        <div className="pitch-heat-grid" aria-hidden="true">
          {bins.map((weight, i) => (
            <span
              key={i}
              className="pitch-heat-cell"
              style={{
                opacity: weight === 0 ? 0 : 0.15 + weight * 0.65,
              }}
              data-testid={`pitch-heat-cell-${i}`}
            />
          ))}
        </div>
      )}

      {positions.map((m, i) => (
        <span
          key={i}
          className="pitch-marker"
          style={{ left: `${m.x * 100}%`, top: `${m.y * 100}%` }}
          data-testid={`pitch-marker-${i}`}
        >
          {m.label}
        </span>
      ))}

      <span className="pitch-label" data-testid={`${testId}-label`}>
        {caption || (heatCells ? "Positional intensity" : "Structural view")}
      </span>
    </div>
  );
}
