"""Phase 13 — Football Decision Intelligence 2.0.

Defines canonical release states, epistemic modalities, and simulation enums.
"""
from enum import Enum

PHASE_13_VERSION = "13.0.0"


class Phase13ReleaseState(str, Enum):
    PHASE_13_IN_PROGRESS = "PHASE_13_IN_PROGRESS"
    SCENARIO_ENGINE_VALIDATED = "SCENARIO_ENGINE_VALIDATED"
    DECISION_SIMULATION_VALIDATED = "DECISION_SIMULATION_VALIDATED"
    RECRUITMENT_SCENARIO_VALIDATED = "RECRUITMENT_SCENARIO_VALIDATED"
    PHASE_13_RELEASE_BLOCKED = "PHASE_13_RELEASE_BLOCKED"


class EpistemicModality(str, Enum):
    OBSERVED = "OBSERVED"
    MODELLED = "MODELLED"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    SCENARIO = "SCENARIO"
    ASSUMPTION = "ASSUMPTION"


class SquadDepthState(str, Enum):
    SOLID = "SOLID"
    ADEQUATE = "ADEQUATE"
    THIN = "THIN"
    CRITICAL_GAP = "CRITICAL_GAP"


class TacticalDiagnosticState(str, Enum):
    OPTIMAL = "OPTIMAL"
    TACTICAL_GAP = "TACTICAL_GAP"
    ROLE_OVERLOAD = "ROLE_OVERLOAD"
    ROLE_UNDERCOVERAGE = "ROLE_UNDERCOVERAGE"
    POSITIONAL_REDUNDANCY = "POSITIONAL_REDUNDANCY"
    FORMATION_UNSUPPORTED = "FORMATION_UNSUPPORTED"


class AcademyReadinessState(str, Enum):
    NOT_READY = "NOT_READY"
    DEVELOPMENTAL = "DEVELOPMENTAL"
    ROTATION_READY = "ROTATION_READY"
    SQUAD_READY = "SQUAD_READY"


class ScenarioRobustnessClass(str, Enum):
    STABLE = "STABLE"
    SENSITIVE = "SENSITIVE"
    HIGHLY_SENSITIVE = "HIGHLY_SENSITIVE"
