"""Phase 12 — Continuous Learning, Advanced Recruitment Intelligence & Decision Evolution.

Defines canonical release states, lifecycle enums, and package versioning.
"""
from enum import Enum

PHASE_12_VERSION = "12.0.0"


class Phase12ReleaseState(str, Enum):
    PHASE_12_IN_PROGRESS = "PHASE_12_IN_PROGRESS"
    LEARNING_PIPELINE_VALIDATED = "LEARNING_PIPELINE_VALIDATED"
    CONTINUOUS_INTELLIGENCE_VALIDATED = "CONTINUOUS_INTELLIGENCE_VALIDATED"
    RECRUITMENT_INTELLIGENCE_VALIDATED = "RECRUITMENT_INTELLIGENCE_VALIDATED"
    PHASE_12_RELEASE_BLOCKED = "PHASE_12_RELEASE_BLOCKED"


class DecisionFreshnessState(str, Enum):
    CURRENT = "CURRENT"
    MONITOR = "MONITOR"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class CandidateDiscoveryMode(str, Enum):
    ROLE_SIMILAR = "ROLE_SIMILAR"
    CONTRIBUTION_SIMILAR = "CONTRIBUTION_SIMILAR"
    TACTICAL_SIMILAR = "TACTICAL_SIMILAR"
    MARKET_VALUE_GAP = "MARKET_VALUE_GAP"
    EMERGING = "EMERGING"
    REPLACEMENT = "REPLACEMENT"
    SCENARIO_CONSTRAINED = "SCENARIO_CONSTRAINED"


class RetrainRecommendation(str, Enum):
    RETRAIN_RECOMMENDED = "RETRAIN_RECOMMENDED"
    NO_RETRAIN_REQUIRED = "NO_RETRAIN_REQUIRED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class DecisionOutcomeAlignment(str, Enum):
    ALIGNED = "ALIGNED"
    PARTIALLY_ALIGNED = "PARTIALLY_ALIGNED"
    DIVERGED = "DIVERGED"
    INSUFFICIENT_FOLLOWUP = "INSUFFICIENT_FOLLOWUP"


class MarketOpportunityState(str, Enum):
    NO_SIGNAL = "NO_SIGNAL"
    WATCH = "WATCH"
    POTENTIAL_VALUE_GAP = "POTENTIAL_VALUE_GAP"
    HIGH_DATA_CONFIDENCE_VALUE_GAP = "HIGH_DATA_CONFIDENCE_VALUE_GAP"
