import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Database, Search, SlidersHorizontal } from "lucide-react";
import { apiErrorMessage, getPlayers } from "@/lib/footballApi";

export default function PlayerSearchPage() {
  const [search, setSearch] = useState("");
  const [position, setPosition] = useState("");
  const players = useQuery({ queryKey: ["players", position], queryFn: () => getPlayers(position ? { position } : {}), staleTime: 60000 });
  const filtered = useMemo(() => (players.data || []).filter((player) => player.name.toLowerCase().includes(search.toLowerCase())), [players.data, search]);
  return <section className="intelligence-page" data-testid="player-search-page"><div className="page-heading"><div><p className="eyebrow" data-testid="page-eyebrow">INTELLIGENCE / PLAYERS</p><h1 data-testid="page-title">Player discovery</h1><p className="workspace-subtitle" data-testid="page-description">Search the connected player universe by identity, position, and evidence.</p></div><span className="contract-badge" data-testid="api-contract-badge">LIVE API CONTRACT</span></div><div className="workspace-toolbar player-toolbar" data-testid="player-filter-bar"><label className="command-input"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search player name" aria-label="Search player name" data-testid="player-search-input" /></label><label className="select-control"><SlidersHorizontal size={16} /><select value={position} onChange={(event) => setPosition(event.target.value)} aria-label="Filter by position" data-testid="player-position-filter"><option value="">All positions</option><option value="GK">GK</option><option value="D">Defender</option><option value="M">Midfielder</option><option value="F">Forward</option></select></label></div>{players.isLoading && <p className="inline-state" data-testid="players-loading-state">Loading connected player data…</p>}{players.isError && <div className="inline-state error-state" data-testid="players-error-state"><Database size={18} /><span>{apiErrorMessage(players.error)}</span></div>}{!players.isLoading && !players.isError && <div className="player-table-wrap" data-testid="player-table"><table><thead><tr><th>PLAYER</th><th>POSITION</th><th>NATIONALITY</th><th>SEASON RECORDS</th><th /></tr></thead><tbody>{filtered.map((player) => <tr key={player.id} data-testid={`player-row-${player.id}`}><td><Link to={`/players/${player.id}`} className="player-link" data-testid={`player-link-${player.id}`}>{player.name}</Link></td><td data-testid={`player-position-${player.id}`}>{player.primary_position || "Insufficient data"}</td><td data-testid={`player-nationality-${player.id}`}>{player.nationality || "Insufficient data"}</td><td data-testid={`player-seasons-${player.id}`}>{player.season_stats?.length || 0}</td><td><Link to={`/players/${player.id}`} className="row-action" data-testid={`player-open-${player.id}`}>Open profile</Link></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="table-empty" data-testid="players-empty-state">No players matched the connected API response.</div>}</div>}</section>;
}