"""Persistent operational state (Phase 18, R12).

Project members, a durable worker task queue (lease + idempotency key +
bounded retries), scheduled job definitions, worker heartbeats, freshness
records and measured operational metrics. Everything that must survive an
API, worker or Redis restart lives here.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-01 17:49:59.132501
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_operational_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_operational_metrics_metric'), 'ops_operational_metrics', ['metric'], unique=False)
    op.create_table('ops_scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ops_worker_heartbeats',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('ops_worker_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_worker_task_idempotency')
    )
    op.create_index(op.f('ix_ops_worker_tasks_job_type'), 'ops_worker_tasks', ['job_type'], unique=False)
    op.create_index(op.f('ix_ops_worker_tasks_not_before'), 'ops_worker_tasks', ['not_before'], unique=False)
    op.create_index(op.f('ix_ops_worker_tasks_status'), 'ops_worker_tasks', ['status'], unique=False)
    op.create_table('ops_freshness_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_season_id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.String(length=128), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['competition_season_id'], ['competition_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['ops_worker_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_freshness_records_competition_season_id'), 'ops_freshness_records', ['competition_season_id'], unique=False)
    op.create_index(op.f('ix_ops_freshness_records_computed_at'), 'ops_freshness_records', ['computed_at'], unique=False)
    op.create_table('ops_project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['ops_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ops_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_ops_project_members_project_id'), 'ops_project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_ops_project_members_user_id'), 'ops_project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_project_members_user_id'), table_name='ops_project_members')
    op.drop_index(op.f('ix_ops_project_members_project_id'), table_name='ops_project_members')
    op.drop_table('ops_project_members')
    op.drop_index(op.f('ix_ops_freshness_records_computed_at'), table_name='ops_freshness_records')
    op.drop_index(op.f('ix_ops_freshness_records_competition_season_id'), table_name='ops_freshness_records')
    op.drop_table('ops_freshness_records')
    op.drop_index(op.f('ix_ops_worker_tasks_status'), table_name='ops_worker_tasks')
    op.drop_index(op.f('ix_ops_worker_tasks_not_before'), table_name='ops_worker_tasks')
    op.drop_index(op.f('ix_ops_worker_tasks_job_type'), table_name='ops_worker_tasks')
    op.drop_table('ops_worker_tasks')
    op.drop_table('ops_worker_heartbeats')
    op.drop_table('ops_scheduled_jobs')
    op.drop_index(op.f('ix_ops_operational_metrics_metric'), table_name='ops_operational_metrics')
    op.drop_table('ops_operational_metrics')
    # ### end Alembic commands ###
