"""Authoritative model registry (Phase 18, R8 / R18 / R20).

Adds artifact URI, dataset SHA-256, windows, horizons, lineage and
reproduction status, and promotion provenance to ops_model_registry, and
moves deployment_state to the Phase 18 vocabulary:
REGISTERED -> CANDIDATE, ACTIVE -> PRODUCTION (SHADOW unchanged).

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-01 17:54:47.529880
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ops_model_registry', sa.Column('artifact_uri', sa.String(length=1024), nullable=True))
    op.add_column('ops_model_registry', sa.Column('dataset_sha256', sa.String(length=64), nullable=True))
    op.add_column('ops_model_registry', sa.Column('windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ops_model_registry', sa.Column('supported_horizons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ops_model_registry', sa.Column('lineage_status', sa.String(length=32), nullable=True))
    op.add_column('ops_model_registry', sa.Column('reproduction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ops_model_registry', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('ops_model_registry', sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ops_model_registry', sa.Column('promoted_by', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_ops_model_registry_promoted_by', 'ops_model_registry', 'ops_users', ['promoted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    op.execute("UPDATE ops_model_registry SET deployment_state = 'CANDIDATE' WHERE deployment_state = 'REGISTERED'")
    op.execute("UPDATE ops_model_registry SET deployment_state = 'PRODUCTION' WHERE deployment_state = 'ACTIVE'")


def downgrade() -> None:
    op.execute("UPDATE ops_model_registry SET deployment_state = 'REGISTERED' WHERE deployment_state = 'CANDIDATE'")
    op.execute("UPDATE ops_model_registry SET deployment_state = 'ACTIVE' WHERE deployment_state = 'PRODUCTION'")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_ops_model_registry_promoted_by', 'ops_model_registry', type_='foreignkey')
    op.drop_column('ops_model_registry', 'promoted_by')
    op.drop_column('ops_model_registry', 'promoted_at')
    op.drop_column('ops_model_registry', 'status_reason')
    op.drop_column('ops_model_registry', 'reproduction')
    op.drop_column('ops_model_registry', 'lineage_status')
    op.drop_column('ops_model_registry', 'supported_horizons')
    op.drop_column('ops_model_registry', 'windows')
    op.drop_column('ops_model_registry', 'dataset_sha256')
    op.drop_column('ops_model_registry', 'artifact_uri')
    # ### end Alembic commands ###
