"""Phase 15: Global Football Research, Adaptive Intelligence & Cross-Competition Generalization.

Architectural Doctrine:
- Strict epistemic modality segregation: OBSERVED, MODELLED, COUNTERFACTUAL, SCENARIO, ASSUMPTION, ANALYSIS, HYPOTHESIS.
- Explicit research lifecycle: DISCOVERED -> HYPOTHESIS -> TESTING -> VALIDATED / REJECTED / INSUFFICIENT_EVIDENCE -> PRODUCTION_CANDIDATE -> PROMOTED.
- Discovery != Validation != Production Adoption.
- Non-causal policy: Prohibit causal claims; mandate associative descriptive language.
- Zero fabrication: Missing data must be explicitly reported as INSUFFICIENT_DATA or UNAVAILABLE.
"""

from enum import Enum


class Phase15ReleaseState(str, Enum):
    PHASE_15_IN_PROGRESS = "PHASE_15_IN_PROGRESS"
    RESEARCH_FOUNDATION_VALIDATED = "RESEARCH_FOUNDATION_VALIDATED"
    PATTERN_DISCOVERY_VALIDATED = "PATTERN_DISCOVERY_VALIDATED"
    CROSS_COMPETITION_VALIDATED = "CROSS_COMPETITION_VALIDATED"
    RESEARCH_VALIDATED = "RESEARCH_VALIDATED"
    ADAPTIVE_INTELLIGENCE_VALIDATED = "ADAPTIVE_INTELLIGENCE_VALIDATED"
    PHASE_15_RELEASE_BLOCKED = "PHASE_15_RELEASE_BLOCKED"


class EpistemicModality(str, Enum):
    OBSERVED = "OBSERVED"
    MODELLED = "MODELLED"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    SCENARIO = "SCENARIO"
    ASSUMPTION = "ASSUMPTION"
    ANALYSIS = "ANALYSIS"
    HYPOTHESIS = "HYPOTHESIS"


class ResearchLifecycleState(str, Enum):
    DISCOVERED = "DISCOVERED"
    HYPOTHESIS = "HYPOTHESIS"
    TESTING = "TESTING"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    PRODUCTION_CANDIDATE = "PRODUCTION_CANDIDATE"
    PROMOTED = "PROMOTED"


class PatternFamily(str, Enum):
    PLAYER_TRAJECTORY = "PLAYER_TRAJECTORY"
    ROLE_TRANSITION = "ROLE_TRANSITION"
    TACTICAL_STRUCTURE = "TACTICAL_STRUCTURE"
    SQUAD_CONSTRUCTION = "SQUAD_CONSTRUCTION"
    TRANSFER_MARKET = "TRANSFER_MARKET"
    PLAYER_DEVELOPMENT = "PLAYER_DEVELOPMENT"
    MATCH_CONTEXT = "MATCH_CONTEXT"
    COMPETITION_STYLE = "COMPETITION_STYLE"
    DECISION_OUTCOME = "DECISION_OUTCOME"
    MODEL_ERROR = "MODEL_ERROR"


class GeneralizationDomain(str, Enum):
    IN_DOMAIN = "IN_DOMAIN"
    CROSS_DOMAIN = "CROSS_DOMAIN"
    LOW_SUPPORT = "LOW_SUPPORT"
    OOD = "OOD"


class ValidationMatrixStatus(str, Enum):
    VALIDATED = "VALIDATED"
    PARTIALLY_VALIDATED = "PARTIALLY_VALIDATED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNCALIBRATED = "UNCALIBRATED"
    OOD = "OOD"
    NOT_EVALUATED = "NOT_EVALUATED"


class RoleTransitionStatus(str, Enum):
    ROLE_TRANSITION_CONFIRMED = "ROLE_TRANSITION_CONFIRMED"
    ROLE_TRANSITION_POSSIBLE = "ROLE_TRANSITION_POSSIBLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class FeeTaxonomy(str, Enum):
    KNOWN_FEE = "KNOWN_FEE"
    REPORTED_FEE = "REPORTED_FEE"
    ESTIMATED_FEE = "ESTIMATED_FEE"
    UNKNOWN_FEE = "UNKNOWN_FEE"
    FREE_TRANSFER = "FREE_TRANSFER"
    LOAN = "LOAN"
    LOAN_WITH_OPTION = "LOAN_WITH_OPTION"
    LOAN_WITH_OBLIGATION = "LOAN_WITH_OBLIGATION"
    UNDISCLOSED = "UNDISCLOSED"


class DataSufficiencyStatus(str, Enum):
    DATA_AVAILABLE = "DATA_AVAILABLE"
    LOW_SAMPLE = "LOW_SAMPLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    OOD = "OOD"
    UNAVAILABLE = "UNAVAILABLE"


class HypothesisValidationResult(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class TrajectoryClass(str, Enum):
    SUSTAINED_IMPROVEMENT = "sustained_improvement"
    SUSTAINED_DECLINE = "sustained_decline"
    ROLE_TRANSITION = "role_transition"
    OPPORTUNITY_DRIVEN_BREAKOUT = "opportunity_driven_breakout"
    MINUTES_DRIVEN_APPARENT_BREAKOUT = "minutes_driven_apparent_breakout"
    COMPETITION_TRANSITION = "competition_transition"
    TACTICAL_TRANSITION = "tactical_transition"
    STABLE = "stable"
