"""Phase 14 — Outcome-Aware Decision Intelligence, Realized-Outcome Learning & Advanced Football Research OS.

Canonical contracts, epistemic modalities, error taxonomy, and release states.
Strict non-causal policy: Observed, Modelled, Counterfactual, Scenario, and Assumption
remain segregated at every analytical boundary.
"""
from __future__ import annotations

from enum import Enum


class Phase14ReleaseState(str, Enum):
    PHASE_14_IN_PROGRESS = "PHASE_14_IN_PROGRESS"
    OUTCOME_LEDGER_VALIDATED = "OUTCOME_LEDGER_VALIDATED"
    DECISION_REALIZATION_VALIDATED = "DECISION_REALIZATION_VALIDATED"
    MODEL_FEEDBACK_VALIDATED = "MODEL_FEEDBACK_VALIDATED"
    OUTCOME_INTELLIGENCE_VALIDATED = "OUTCOME_INTELLIGENCE_VALIDATED"
    PHASE_14_RELEASE_BLOCKED = "PHASE_14_RELEASE_BLOCKED"


class EpistemicModality(str, Enum):
    OBSERVED = "OBSERVED"
    MODELLED = "MODELLED"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    SCENARIO = "SCENARIO"
    ASSUMPTION = "ASSUMPTION"
    ANALYSIS = "ANALYSIS"
    HYPOTHESIS = "HYPOTHESIS"


class OutcomeType(str, Enum):
    PLAYER_PERFORMANCE = "PLAYER_PERFORMANCE"
    TRANSFER_REALIZATION = "TRANSFER_REALIZATION"
    TEAM_PERFORMANCE = "TEAM_PERFORMANCE"
    TACTICAL_REALIZATION = "TACTICAL_REALIZATION"
    SQUAD_DEPTH = "SQUAD_DEPTH"
    AVAILABILITY = "AVAILABILITY"
    FINANCIAL = "FINANCIAL"
    DEVELOPMENT = "DEVELOPMENT"
    ACADEMY_PROGRESS = "ACADEMY_PROGRESS"
    ROLE_REALIZATION = "ROLE_REALIZATION"
    MATCH_OUTCOME = "MATCH_OUTCOME"
    MODEL_PREDICTION_REALIZATION = "MODEL_PREDICTION_REALIZATION"
    DECISION_PROCESS = "DECISION_PROCESS"


class AlignmentClassification(str, Enum):
    ALIGNED = "ALIGNED"
    PARTIALLY_ALIGNED = "PARTIALLY_ALIGNED"
    DIVERGED = "DIVERGED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class DataSufficiencyStatus(str, Enum):
    DATA_AVAILABLE = "DATA_AVAILABLE"
    LOW_SAMPLE = "LOW_SAMPLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    OUT_OF_DISTRIBUTION = "OUT_OF_DISTRIBUTION"
    UNAVAILABLE = "UNAVAILABLE"


class ErrorCategory(str, Enum):
    DATA_ERROR = "DATA_ERROR"
    DATA_SPARSE = "DATA_SPARSE"
    TEMPORAL_MISMATCH = "TEMPORAL_MISMATCH"
    MODEL_ERROR = "MODEL_ERROR"
    CALIBRATION_ERROR = "CALIBRATION_ERROR"
    OOD_ERROR = "OOD_ERROR"
    ASSUMPTION_ERROR = "ASSUMPTION_ERROR"
    SCENARIO_ERROR = "SCENARIO_ERROR"
    EXECUTION_DIVERGENCE = "EXECUTION_DIVERGENCE"
    UNOBSERVED_EXTERNAL_FACTOR = "UNOBSERVED_EXTERNAL_FACTOR"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class DecisionProcessState(str, Enum):
    WELL_SUPPORTED = "WELL_SUPPORTED"
    SUPPORTED_WITH_LIMITATIONS = "SUPPORTED_WITH_LIMITATIONS"
    DATA_LIMITED = "DATA_LIMITED"
    MODEL_LIMITED = "MODEL_LIMITED"
    SCENARIO_LIMITED = "SCENARIO_LIMITED"
    EVIDENCE_LIMITED = "EVIDENCE_LIMITED"


class LearningActionState(str, Enum):
    NO_ACTION = "NO_ACTION"
    MONITOR = "MONITOR"
    INVESTIGATE = "INVESTIGATE"
    RETRAIN_RECOMMENDED = "RETRAIN_RECOMMENDED"
    CHALLENGER_RECOMMENDED = "CHALLENGER_RECOMMENDED"
    VALIDATION_REQUIRED = "VALIDATION_REQUIRED"
    PROMOTION_CANDIDATE = "PROMOTION_CANDIDATE"


class FreshnessState(str, Enum):
    FRESH = "FRESH"
    AGING = "AGING"
    STALE = "STALE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class TacticalRealizationState(str, Enum):
    TACTICAL_ALIGNMENT = "TACTICAL_ALIGNMENT"
    TACTICAL_PARTIAL_ALIGNMENT = "TACTICAL_PARTIAL_ALIGNMENT"
    TACTICAL_DIVERGENCE = "TACTICAL_DIVERGENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ScenarioRealizationStatus(str, Enum):
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    EVALUATED = "EVALUATED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class BenchmarkScope(str, Enum):
    CURRENT_BENCHMARK = "CURRENT_BENCHMARK"
    HISTORICAL_BENCHMARK = "HISTORICAL_BENCHMARK"
    DECISION_TIME_BENCHMARK = "DECISION_TIME_BENCHMARK"
